# Generated by Django 6.0.5 on 2026-05-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255)),
                ('book_author', models.CharField(max_length=255)),
                ('page_number', models.IntegerField()),
                ('book_format', models.CharField(max_length=255)),
                ('book_image', models.ImageField(upload_to='')),
                ('book_price', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='review_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_review_title', models.CharField(max_length=255)),
                ('book_review_author', models.CharField(max_length=255)),
                ('review_rate', models.IntegerField()),
                ('review_description', models.TextField(max_length=1000)),
                ('review_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
