# Generated by Django 6.0.5 on 2026-05-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_model',
            name='book_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='review_model',
            name='review_book_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
