# Generated by Django 6.1.1 on 2026-09-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_book_model_book_file_review_model_review_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_model',
            name='book_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book_model',
            name='book_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
