# Generated by Django 6.1.1 on 2026-09-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_book_model_book_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_doc', models.FileField(blank=True, max_length=255, null=True, upload_to='')),
            ],
        ),
    ]
